#! namespace, sa, {cluster,}role{binding,} names will be overlayed
---
apiVersion: v1
kind: Namespace
metadata: {}
---
apiVersion: v1
kind: ServiceAccount
metadata: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
  resourceNames:
  - prom-proxy-config
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
  resourceNames:
  - prom-proxy-htpasswd
  - prom-proxy-tls
- apiGroups: [""]
  resources: ["deployments", "ingresses", "httpproxies"]
  verbs: ["*"]
  resourceNames:
  - prom-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
subjects:
- kind: ServiceAccount
